### ISSUE TITLE
If I want to reproduce the code, which file should I run?

### ISSUE THREAD

**Issue by yuanyuan-star** [JJ-Vice/BAGM#1]

**Comment by JJ-Vice** [comment]
Hi! 

If you want to generate images using a backdoored model you can use the "Image Generation.ipynb" notebook.
If you want to assess generated images using our metrics, use the "Metric Generation.ipynb" notebook.

We have not made our backdoored models publicly available yet, but these backdoored models can be replicated using the MF Dataset: https://ieee-dataport.org/documents/marketable-foods-mf-dataset. There are fine-tuning tutorials on HuggingFace which we found particularly useful when injecting our backdoors: https://huggingface.co/docs/diffusers/v0.13.0/en/training/text2image 

Through the dataset, the published article and the tutorial you can replicate our models and use the code on this repo to generate images and evaluate models.

Hope this helps!

Jordan
